In [1]:
from tensorflow import keras

(train_input, train_target), (test_input, test_target) = keras.datasets.fashion_mnist.load_data()

In [2]:
from sklearn.model_selection import train_test_split

train_scaled = train_input / 255
train_scaled = train_scaled.reshape(-1, 28*28)
test_scaled=test_input/255
test_scaled=test_scaled.reshape(-1, 28*28)

In [3]:
input=keras.layers.Input(shape=(784,))
hidden=keras.layers.Dense(100, activation="sigmoid")
output=keras.layers.Dense(10, activation="softmax")

In [4]:
model = keras.Sequential()
model.add(input)
model.add(hidden)
model.add(output)

In [5]:
model = keras.Sequential([
    keras.layers.Dense(100, activation='sigmoid', input_shape=(784,), name='hidden'),
    keras.layers.Dense(10, activation='softmax', name='output')
])

D:\mldl\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.compile(loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(train_scaled, train_target, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7619 - loss: 0.7327
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8561 - loss: 0.4023
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 999us/step - accuracy: 0.8662 - loss: 0.3666
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 995us/step - accuracy: 0.8763 - loss: 0.3445
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 998us/step - accuracy: 0.8837 - loss: 0.3244


In [7]:
model.evaluate(test_scaled,test_target)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.8592 - loss: 0.3948


[0.3923950791358948, 0.8579999804496765]

In [14]:
predictions=model.predict(test_scaled[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


In [15]:
predictions= predictions.argmax(axis=1)
print(predictions)

[9 2 1 1 6]


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
